# NumPy Exercises

This notebook contains 10 simple NumPy exercises with code and outputs.

## Exercise 1: Array Creation and Manipulation

In [1]:
import numpy as np

arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 2: Type Conversion and Array Operations

In [2]:
arr2 = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
arr2

array([3, 2, 0, 1, 2])

## Exercise 3: Working with Multi-Dimensional Arrays

In [3]:
arr3 = np.arange(1, 10).reshape(3, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 4: Creating Multi-Dimensional Array with Random Numbers

In [4]:
np.random.seed(42)
arr4 = np.random.rand(4, 5).round(2)
arr4

array([[0.37, 0.95, 0.73, 0.6 , 0.16],
       [0.16, 0.06, 0.87, 0.6 , 0.71],
       [0.02, 0.97, 0.83, 0.21, 0.18],
       [0.18, 0.3 , 0.52, 0.43, 0.29]])

## Exercise 5: Indexing Arrays

In [5]:
arr5 = np.array([[21, 22, 23, 22, 22],
                 [20, 21, 22, 23, 24],
                 [21, 22, 23, 22, 22]])

second_row = arr5[1]
second_row

array([20, 21, 22, 23, 24])

## Exercise 6: Reversing Elements

In [6]:
arr6 = np.arange(10)
arr6[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Exercise 7: Identity Matrix

In [7]:
arr7 = np.identity(4)
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Exercise 8: Simple Aggregate Functions

In [8]:
arr8 = np.arange(10)
array_sum = arr8.sum()
array_avg = arr8.mean()
print(f"Sum: {array_sum}, Average: {array_avg}")

Sum: 45, Average: 4.5


## Exercise 9: Create Array and Change its Structure

In [9]:
arr9 = np.arange(1, 21).reshape(4, 5)
arr9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Exercise 10: Conditional Selection of Values

In [10]:
arr10 = np.arange(1, 11)
arr10[arr10 % 2 == 1]

array([1, 3, 5, 7, 9])